feat: support one line install => curl -o- https://raw.githubusercontent.com/zmicro-design/package-mtg/master/install | sh -s -- ONE_LINE

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,18 +1,16 @@
 #!/bin/bash
 
-VERSION=v0.19.0
-
-set -e
+VERSION=v2.1.7
 
 help() {
   echo "Usage:"
-  echo "  zmicro package install lazydocker <args...>"
+  echo "  zmicro package install mtg <args...>"
   echo ""
 }
 
 install() {
   # prepare vars
-  local name="lazydocker"
+  local name="mtg"
   # get system os/arch
   local arch="$(os::arch)"
   local kernel="$(os::kernel)"
@@ -22,27 +20,18 @@ install() {
   local tmp_dir="/tmp/$name"
   # files
   local tmp_file="$name.tar.gz"
-  local bin_file="$name"
-
-  if [ "$arch" = "amd64" ]; then
-    arch="x86_64"
-  elif [ "$arch" = "arm64" ]; then
-    arch="arm64"
-  else
-    log::error "unknown architecture: $arch"
-    exit 1
-  fi
+  local bin_file="./${name}-${VERSION#v}-${platform}-${arch}/$name"
 
   # prepare context
   mkdir -p $tmp_dir
   cd $tmp_dir
 
-  # reference: https://github.com/jesseduffield/lazydocker/releases
+  # reference: https://github.com/9seconds/mtg/releases
   # example:
-  #   https://github.com/jesseduffield/lazydocker/releases/download/v0.19.0/lazydocker_0.19.0_Darwin_arm64.tar.gz
-  #   https://github.com/jesseduffield/lazydocker/releases/download/v0.19.0/lazydocker_0.19.0_Darwin_x86_64.tar.gz
+  #   https://github.com/9seconds/mtg/releases/download/v2.1.7/mtg-2.1.7-darwin-arm64.tar.gz
+  #   https://github.com/9seconds/mtg/releases/download/v2.1.7/mtg-2.1.7-darwin-amd64.tar.gz
   # generate url
-  local url="https://github.com/jesseduffield/lazydocker/releases/download/$VERSION/${name}_${VERSION#v}_${kernel}_${arch}.tar.gz"
+  local url="https://github.com/9seconds/mtg/releases/download/$VERSION/${name}-${VERSION#v}-${platform}-${arch}.tar.gz"
   log::debug "[package][$name][$kernel][$arch] url: $url"
 
   # download
@@ -66,16 +55,27 @@ core() {
 
   install
   if [ $? -eq 0 ]; then
-    log::success "install lazydocker success."
+    log::success "install mtg success."
     exit 0
   else
-    log::error "install lazydocker failed."
+    log::error "install mtg failed."
     exit 1
   fi
 }
 
 run() {
-  core $@
+  core "$@"
 }
 
-run $@
+if [ "$1" = "ONE_LINE" ]; then
+  command -v zmicro # >>/dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | sh
+  fi
+
+  zmicro package install mtg
+else
+  set -e
+  
+  run "$@"
+fi
